% enclose peptide sequences in double quotes " " and separate by commas

peptides = ["TRSSRAGLQWPVGRVHRLLRK", "XTRSXSAGLQWPVGRVHRLLRK", "XRSSXAGLQWPVGRVHRLLRK", "TXSSRXGLQWPVGRVHRLLRK", "TRXSRAXLQWPVGRVHRLLRK", "TRSXRAGXQWPVGRVHRLLRK", "TRSSXAGLXWPVGRVHRLLRK", "TRSSRXGLQXPVGRVHRLLRK", "TRSSRAXLQWXVGRVHRLLRK", "TRSSRAGXQWPXGRVHRLLRK", "TRSSRAGLXWPVXRVHRLLRK", "TRSSRAGLQXPVGXVHRLLRK", "TRSSRAGLQWXVGRXHRLLRK", "TRSSRAGLQWPXGRVXRLLRK", "TRSSRAGLQWPVXRVHXLLRK", "TRSSRAGLQWPVGXVHRXLRK", "TRSSRAGLQWPVGRXHRLXRK", "TRSSRAGLQWPVGRVXRLLXK", "TRSSRAGLQWPVGRVHXLLRX", "KRSSRAGLQWPXGRVXRLLRK", "TKSSRAGLQWPXGRVXRLLRK", "TRKSRAGLQWPXGRVXRLLRK", "TRSKRAGLQWPXGRVXRLLRK", "TRSSKAGLQWPXGRVXRLLRK", "TRSSRKGLQWPXGRVXRLLRK", "TRSSRAKLQWPXGRVXRLLRK", "TRSSRAGKQWPXGRVXRLLRK", "TRSSRAGLKWPXGRVXRLLRK", "TRSSRAGLQKPXGRVXRLLRK", "TRSSRAGLQWKXGRVXRLLRK", "TRSSRAGLQWPXKRVXRLLRK", "TRSSRAGLQWPXGKVXRLLRK", "TRSSRAGLQWPXGRKXRLLRK", "TRSSRAGLQWPXGRVXKLLRK", "TRSSRAGLQWPXGRVXRKLRK", "TRSSRAGLQWPXGRVXKLKRK", "TRSSRAGLQWPXGRVXRLLKK"];

lyticity_values=[];
for i=1:length(peptides)
    lyticity_values(i) = calculate_lyticity(peptides(i))
end

